### ISSUE TITLE
Failed to access Docker

### ISSUE THREAD

**Issue by patrickacraig** [langchain-ai/langgraph-studio#110]
When I start LangGraph Studio, I am getting the following error notification:

`Failed to access Docker: Unexpected token 'j', "json" is not valid JSON`

I have reinstalled Docker and LangGraph Studio, but the issue persists. Note that this error occurs before attempting to open any particular folder. 

<img width="1199" alt="Screenshot 2024-09-11 at 12 05 12 PM" src="https://github.com/user-attachments/assets/f3ac00cd-3dcb-46ea-85bb-3cc352191f61">

Any ideas on how to troubleshoot/fix would be greatly appreciated.

**Comment by dqbd** [comment]
Hello @patrickacraig! Could you share the output of `docker info -f json` or `docker info`?

**Comment by patrickacraig** [comment]
```(lc-academy-env) (base) patrickcraig@Patricks-MacBook-Pro langchain-academy % docker info
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /Users/patrickcraig/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.655GiB
 Name: docker-desktop
 # ID Redacted
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 # HTTP Proxy settings redacted
 Registry: https://index.docker.io/v1/
 Labels:
  com.docker.desktop.address=unix:///Users/patrickcraig/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile```

**Comment by patrickacraig** [comment]
@dqbd that was for `docker info -f json`. Let me know if that's not the output you were looking for.

**Comment by patrickacraig** [comment]
Update on this: Installing the Docker CLI tools separately using Homebrew fixed the error. If you encounter the error above, just run `brew install docker docker-compose docker-machine` in your terminal, then run `brew services start docker-machine` and restart Docker Desktop and LangGraph Studio and you should be good to go.

**Comment by devjones** [comment]
Just worked for me after I updated my Docker Desktop version

**Comment by luongnv89** [comment]
I got the same error. Not sure if it relates but I got the error after updating my Macbook (M1) to the latest version of MacOS (Sequoia). Updating Docker Desktop did not work for me!

**Comment by NorberMV** [comment]
I was getting the same error. After upgrading Docker Desktop to 4.34.2 (167172) and launching LanGraph Studio again, everything went smoothly.

**Comment by dqbd** [comment]
Closing this issue, as this issue stems from a too old of a version of Docker Client. For anyone encountering the issue, would either recommend updating your Docker distribution or install Docker CLI from a different source like Homebrew. 

> @patrickacraig Update on this: Installing the Docker CLI tools separately using Homebrew fixed the error. If you encounter the error above, just run `brew install docker docker-compose docker-machine` in your terminal, then run `brew services start docker-machine` and restart Docker Desktop and LangGraph Studio and you should be good to go.

We've also released new studio version 0.0.30, which will attempt to search for Docker binaries in other places as well.

**Comment by nick-galluzzo** [comment]
> Update on this: Installing the Docker CLI tools separately using Homebrew fixed the error. If you encounter the error above, just run `brew install docker docker-compose docker-machine` in your terminal, then run `brew services start docker-machine` and restart Docker Desktop and LangGraph Studio and you should be good to go.

worked for me!

**Comment by its-nikhil** [comment]
Getting the same error
Note: I am using [OrbStack](https://orbstack.dev/) to run docker containers

I have already tried `/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'` but it did not resolve the issue.

$ docker info -f json
```
json
```

---

$ docker info -h
```
Flag shorthand -h has been deprecated, please use --help

Usage:  docker info [OPTIONS]

Display system-wide information

Aliases:
  docker system info, docker info

Options:
  -f, --format string   Format the output using the given Go template
```

---

$ docker info -f '{{json .}}'
```
{"ID":"*****-e28e-4077-ac3c-*****","Containers":7,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":7,"Images":13,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","btrfs"],["Supports d_type","true"],["Using metacopy","false"],["Native Overlay Diff","true"],["userxattr","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":27,"OomKillDisable":false,"NGoroutines":51,"SystemTime":"2024-11-22T13:04:08.589387894+05:30","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"2","NEventsListener":1,"KernelVersion":"****-orbstack-00279-****","OperatingSystem":"OrbStack","OSVersion":"","OSType":"linux","Architecture":"aarch64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":null,"AllowNondistributableArtifactsHostnames":null,"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":null},"NCPU":4,"MemTotal":6276710400,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"orbstack","Labels":[],"ExperimentalBuild":false,"ServerVersion":"27.3.1","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"207ad711eabd375a01713109a8a197d197ff6542","Expected":"207ad711eabd375a01713109a8a197d197ff6542"},"RuncCommit":{"ID":"d7735e388ef5eecbd60d93bfbe5afe0f3fbc8a6b","Expected":"d7735e388ef5eecbd60d93bfbe5afe0f3fbc8a6b"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=builtin","name=cgroupns"],"ProductLicense":"Community Engine","DefaultAddressPools":[{...}],"Warnings":null,"ClientInfo":{"Debug":false,"Context":"orbstack","Plugins":[{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.18.0","ShortDescription":"Docker Buildx","Name":"buildx","Path":"/Users/****/.docker/cli-plugins/docker-buildx"},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v2.29.7","ShortDescription":"Docker Compose","Name":"compose","Path":"/Users/****/.docker/cli-plugins/docker-compose"}],"Warnings":null}}
```

**Comment by schoolofai** [comment]
ok for me it worked only if i removed docker desktop cleanly and then reinstall the downloading the new docker desktop from - https://docs.docker.com/desktop/setup/install/mac-install/ 
Note clean docker desktop uniinstall was done using the unstall from the troubleshoot menu of docker desktop application - click the little bug symbol on the top right next to the settings cog icon and then click uninstall !

**Comment by sxalexander** [comment]
FYI it also fails when using `colima` on Mac OS as the container runtime.

https://github.com/abiosoft/colima

```
$ docker info -f json
json
```

```
$ docker info
Client:
 Context:    colima
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 8
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-39-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.91GiB
 Name: colima
 ID: 3c0ecfe2-ec17-4f5a-997f-7c4d738eb74a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
